### PR TITLE
Pen speed control

### PR DESCRIPTION
**Pull request by drskullster**
Here's a a PR to handle pen speed control in HPGL. 

There is also a check in `selectPen()` method (a simple if else condition) so it doesn't throw an error when used outside of `beginRecord()` method.

I would be happy to contribute to this library but I'm not familiar with Processing Library system. How are the updates pushed to Processing ?

Also, @ciaron is it possible to open the Issue Tracker ? I have questions about the size variables but I didn't find a way to reach you :)

### CODE REVIEW

**Comment by ciaron** [comment]
Thanks for this pull request! It's now merged. The issue tracker is enabled now too.

**Comment by drskullster** [comment]
Hi @ciaron, it's still 1.0.3 on Processing Contribution Manager. How can we push 1.0.4 there ? Is it something I can do ?

**Comment by ciaron** [comment]
Hi @drskullster - that's down to me, I'm afraid. Libraries need to have a "homepage" registered with the Contribution Manager (in this case ciaron.net/hpglgraphics) which is where the library is installed from.

So I need to do a build, test and update the library .zip on the website. I'll try and get round to it this week, but I'm travelling at the moment.

(If you've done your own build, you should have a .zip file that you can install manually yourself)

**Comment by drskullster** [comment]
Thanks for the answer. I do have a working local build so there's no rush :)

**Comment by ciaron** [comment]
Hi again - I had some time so I was able to make an updated build and upload to http://ciaron.net/hpglgraphics - which in turn will be crawled by the Processing Contributions Manager in the next couple of days. 

I also updated your speed.pde example with a comment about checking what the input speed should be (my DXY-1350A, for example, caps this at 42 (mm/sec) but I don't know what other devices will do if given an out-of-range value.)

**Pull request merged**
